#!/bin/sh
# 

. "${PM_FUNCTIONS}"

case "$1" in
	hibernate|suspend)
		;;
	thaw|resume)
		if [ -f /etc/init.d/atd ]; then
			/etc/init.d/atd restart
		elif
			systemctl try-restart atd.service
		fi
		;;
	*) exit $NA
		;;
esac
